# Generated by Django 4.2.7 on 2023-11-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_chat_name_alter_messages_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.TextField(default='chat'),
        ),
    ]
